import { ExamData } from "@/lib/algorithm-types";
import { randomUUID } from "crypto";

// Manually creating the data
const examIdMath = randomUUID();
const mathExamCreatedDate = "2024-08-21";

const examIdEnglish = randomUUID();
const englishExamCreatedDate = "2024-08-25";

const examIdPhysics = randomUUID();
const physicsExamCreatedDate = "2024-08-21";

const topicIdMath1 = randomUUID();
const topicIdMath2 = randomUUID();
const topicIdMath3 = randomUUID();
const topicIdMath4 = randomUUID();
const topicIdMath5 = randomUUID();

const topicIdEnglish1 = randomUUID();
const topicIdEnglish2 = randomUUID();
const topicIdEnglish3 = randomUUID();
const topicIdEnglish4 = randomUUID();
const topicIdEnglish5 = randomUUID();

const topicIdPhysics1 = randomUUID();
const topicIdPhysics2 = randomUUID();
const topicIdPhysics3 = randomUUID();
const topicIdPhysics4 = randomUUID();
const topicIdPhysics5 = randomUUID();

const mathID = randomUUID();
const physicsID = randomUUID();
const englishID = randomUUID();

const userID = randomUUID();

export const sampleExamData: ExamData[] = [
  // {
  //   confidence: null,
  //   confidence_goal: 9,
  //   created_at: mathExamCreatedDate,
  //   exam_date: "2024-08-28",
  //   name: "Math Exam",
  //   last_studied: mathExamCreatedDate,
  //   priority: null,
  //   id: examIdMath,
  //   subject_id: mathID,
  //   subjects: {
  //     subject_name: "Math",
  //     id: mathID,
  //     user_id: userID
  //   },
  //   user_id: userID,
  //   topics: [
  //     {
  //       confidence: null,
  //       exam_id: examIdMath,
  //       id: topicIdMath1,
  //       last_studied: mathExamCreatedDate,
  //       priority: null,
  //       name: "Math Topic 1",
  //       order: 0,
  //       subtopics: [
  //         {
  //           confidence: 5,
  //           id: randomUUID(),
  //           last_studied: mathExamCreatedDate,
  //           priority: null,
  //           name: "Math Subtopic 1.1",
  //           topic_id: topicIdMath1,
  //           order: 0,
  //         },
  //         {
  //           confidence: 6,
  //           id: randomUUID(),
  //           last_studied: mathExamCreatedDate,
  //           priority: null,
  //           name: "Math Subtopic 1.2",
  //           topic_id: topicIdMath1,
  //           order: 0,
  //         },
  //         {
  //           confidence: null,
  //           id: randomUUID(),
  //           last_studied: mathExamCreatedDate,
  //           priority: null,
  //           name: "Math Subtopic 1.3",
  //           topic_id: topicIdMath1,
  //           order: 0,
  //         },
  //         {
  //           confidence: 7,
  //           id: randomUUID(),
  //           last_studied: mathExamCreatedDate,
  //           priority: null,
  //           name: "Math Subtopic 1.4",
  //           topic_id: topicIdMath1,
  //           order: 0,
  //         },
  //         {
  //           confidence: 3,
  //           id: randomUUID(),
  //           last_studied: mathExamCreatedDate,
  //           priority: null,
  //           name: "Math Subtopic 1.5",
  //           topic_id: topicIdMath1,
  //           order: 0,
  //         },
  //       ],
  //     },
  //     {
  //       confidence: null,
  //       exam_id: examIdMath,
  //       id: topicIdMath2,
  //       last_studied: mathExamCreatedDate,
  //       priority: null,
  //       name: "Math Topic 2",
  //       order: 0,
  //       subtopics: [
  //         {
  //           confidence: null,
  //           id: randomUUID(),
  //           last_studied: mathExamCreatedDate,
  //           priority: null,
  //           name: "Math Subtopic 2.1",
  //           topic_id: topicIdMath2,
  //           order: 0,
  //         },
  //         {
  //           confidence: 4,
  //           id: randomUUID(),
  //           last_studied: mathExamCreatedDate,
  //           priority: null,
  //           name: "Math Subtopic 2.2",
  //           topic_id: topicIdMath2,
  //           order: 0,
  //         },
  //         {
  //           confidence: 2,
  //           id: randomUUID(),
  //           last_studied: mathExamCreatedDate,
  //           priority: null,
  //           name: "Math Subtopic 2.3",
  //           topic_id: topicIdMath2,
  //           order: 0,
  //         },
  //         {
  //           confidence: 7,
  //           id: randomUUID(),
  //           last_studied: mathExamCreatedDate,
  //           priority: null,
  //           name: "Math Subtopic 2.4",
  //           topic_id: topicIdMath2,
  //           order: 0,
  //         },
  //         {
  //           confidence: null,
  //           id: randomUUID(),
  //           last_studied: mathExamCreatedDate,
  //           priority: null,
  //           name: "Math Subtopic 2.5",
  //           topic_id: topicIdMath2,
  //           order: 0,
  //         },
  //       ],
  //     },
  //     {
  //       confidence: null,
  //       exam_id: examIdMath,
  //       id: topicIdMath3,
  //       last_studied: mathExamCreatedDate,
  //       priority: null,
  //       name: "Math Topic 3",
  //       order: 0,

  //       subtopics: [
  //         {
  //           confidence: 1,
  //           id: randomUUID(),
  //           last_studied: mathExamCreatedDate,
  //           priority: null,
  //           name: "Math Subtopic 3.1",
  //           topic_id: topicIdMath3,
  //           order: 0,
  //         },
  //         {
  //           confidence: null,
  //           id: randomUUID(),
  //           last_studied: mathExamCreatedDate,
  //           priority: null,
  //           name: "Math Subtopic 3.2",
  //           topic_id: topicIdMath3,
  //           order: 0,
  //         },
  //         {
  //           confidence: 8,
  //           id: randomUUID(),
  //           last_studied: mathExamCreatedDate,
  //           priority: null,
  //           name: "Math Subtopic 3.3",
  //           topic_id: topicIdMath3,
  //           order: 0,
  //         },
  //         {
  //           confidence: 2,
  //           id: randomUUID(),
  //           last_studied: mathExamCreatedDate,
  //           priority: null,
  //           name: "Math Subtopic 3.4",
  //           topic_id: topicIdMath3,
  //           order: 0,
  //         },
  //         {
  //           confidence: null,
  //           id: randomUUID(),
  //           last_studied: mathExamCreatedDate,
  //           priority: null,
  //           name: "Math Subtopic 3.5",
  //           topic_id: topicIdMath3,
  //           order: 0,
  //         },
  //       ],
  //     },
  //     {
  //       confidence: null,
  //       exam_id: examIdMath,
  //       id: topicIdMath4,
  //       last_studied: mathExamCreatedDate,
  //       priority: null,
  //       name: "Math Topic 4",
  //       order: 0,

  //       subtopics: [
  //         {
  //           confidence: 4,
  //           id: randomUUID(),
  //           last_studied: mathExamCreatedDate,
  //           priority: null,
  //           name: "Math Subtopic 4.1",
  //           topic_id: topicIdMath4,
  //           order: 0,
  //         },
  //         {
  //           confidence: 5,
  //           id: randomUUID(),
  //           last_studied: mathExamCreatedDate,
  //           priority: null,
  //           name: "Math Subtopic 4.2",
  //           topic_id: topicIdMath4,
  //           order: 0,
  //         },
  //         {
  //           confidence: 1,
  //           id: randomUUID(),
  //           last_studied: mathExamCreatedDate,
  //           priority: null,
  //           name: "Math Subtopic 4.3",
  //           topic_id: topicIdMath4,
  //           order: 0,
  //         },
  //         {
  //           confidence: null,
  //           id: randomUUID(),
  //           last_studied: mathExamCreatedDate,
  //           priority: null,
  //           name: "Math Subtopic 4.4",
  //           topic_id: topicIdMath4,
  //           order: 0,
  //         },
  //         {
  //           confidence: 3,
  //           id: randomUUID(),
  //           last_studied: mathExamCreatedDate,
  //           priority: null,
  //           name: "Math Subtopic 4.5",
  //           topic_id: topicIdMath4,
  //           order: 0,
  //         },
  //       ],
  //     },
  //     {
  //       confidence: null,
  //       exam_id: examIdMath,
  //       id: topicIdMath5,
  //       last_studied: mathExamCreatedDate,
  //       priority: null,
  //       name: "Math Topic 5",
  //       order: 0,

  //       subtopics: [
  //         {
  //           confidence: 9,
  //           id: randomUUID(),
  //           last_studied: mathExamCreatedDate,
  //           priority: null,
  //           name: "Math Subtopic 5.1",
  //           topic_id: topicIdMath5,
  //           order: 0,
  //         },
  //         {
  //           confidence: 7,
  //           id: randomUUID(),
  //           last_studied: mathExamCreatedDate,
  //           priority: null,
  //           name: "Math Subtopic 5.2",
  //           topic_id: topicIdMath5,
  //           order: 0,
  //         },
  //         {
  //           confidence: null,
  //           id: randomUUID(),
  //           last_studied: mathExamCreatedDate,
  //           priority: null,
  //           name: "Math Subtopic 5.3",
  //           topic_id: topicIdMath5,
  //           order: 0,
  //         },
  //         {
  //           confidence: 8,
  //           id: randomUUID(),
  //           last_studied: mathExamCreatedDate,
  //           priority: null,
  //           name: "Math Subtopic 5.4",
  //           topic_id: topicIdMath5,
  //           order: 0,
  //         },
  //         {
  //           confidence: null,
  //           id: randomUUID(),
  //           last_studied: mathExamCreatedDate,
  //           priority: null,
  //           name: "Math Subtopic 5.5",
  //           topic_id: topicIdMath5,
  //           order: 0,
  //         },
  //       ],
  //     },
  //   ],
  // },
  {
    confidence: null,
    confidence_goal: 9,
    created_at: englishExamCreatedDate,
    exam_date: "2024-09-04",
    name: "English Exam",
    id: examIdEnglish,
    last_studied: englishExamCreatedDate,
    priority: null,
    subject_id: englishID,
    user_id: userID,
    subjects: {
      subject_name: "English",
      id: englishID,
      user_id: userID
    },

    topics: [
      {
        confidence: null,
        exam_id: examIdEnglish,
        id: topicIdEnglish1,
        last_studied: englishExamCreatedDate,
        priority: null,
        name: "English Topic 1",
        order: 0,

        subtopics: [],
      },
      {
        confidence: null,
        exam_id: examIdEnglish,
        id: topicIdEnglish2,
        last_studied: englishExamCreatedDate,
        priority: null,
        name: "English Topic 2",
        order: 0,

        subtopics: [
          {
            confidence: 7,
            id: randomUUID(),
            last_studied: englishExamCreatedDate,
            priority: null,
            name: "English Subtopic 2.1",
            topic_id: topicIdEnglish2,
            order: 0,
          },
        ],
      },
      {
        confidence: null,
        exam_id: examIdEnglish,
        id: topicIdEnglish3,
        last_studied: englishExamCreatedDate,
        priority: null,
        name: "English Topic 3",
        order: 0,

        subtopics: [
          {
            confidence: null,
            id: randomUUID(),
            last_studied: englishExamCreatedDate,
            priority: null,
            name: "English Subtopic 3.1",
            topic_id: topicIdEnglish3,
            order: 0,
          },
          {
            confidence: 5,
            id: randomUUID(),
            last_studied: englishExamCreatedDate,
            priority: null,
            name: "English Subtopic 3.2",
            topic_id: topicIdEnglish3,
            order: 0,
          },
          {
            confidence: 6,
            id: randomUUID(),
            last_studied: englishExamCreatedDate,
            priority: null,
            name: "English Subtopic 3.3",
            topic_id: topicIdEnglish3,
            order: 0,
          },
          {
            confidence: 2,
            id: randomUUID(),
            last_studied: englishExamCreatedDate,
            priority: null,
            name: "English Subtopic 3.4",
            topic_id: topicIdEnglish3,
            order: 0,
          },
          {
            confidence: 3,
            id: randomUUID(),
            last_studied: englishExamCreatedDate,
            priority: null,
            name: "English Subtopic 3.5",
            topic_id: topicIdEnglish3,
            order: 0,
          },
        ],
      },
      {
        confidence: null,
        exam_id: examIdEnglish,
        id: topicIdEnglish4,
        last_studied: englishExamCreatedDate,
        priority: null,
        name: "English Topic 4",
        subtopics: [],
        order: 0,
      },
      {
        confidence: null,
        exam_id: examIdEnglish,
        id: topicIdEnglish5,
        last_studied: englishExamCreatedDate,
        priority: null,
        name: "English Topic 5",
        order: 0,

        subtopics: [
          {
            confidence: null,
            id: randomUUID(),
            last_studied: englishExamCreatedDate,
            priority: null,
            name: "English Subtopic 5.1",
            topic_id: topicIdEnglish5,
            order: 0,
          },
          {
            confidence: 2,
            id: randomUUID(),
            last_studied: englishExamCreatedDate,
            priority: null,
            name: "English Subtopic 5.2",
            topic_id: topicIdEnglish5,
            order: 0,
          },
          {
            confidence: 5,
            id: randomUUID(),
            last_studied: englishExamCreatedDate,
            priority: null,
            name: "English Subtopic 5.3",
            order: 0,

            topic_id: topicIdEnglish5,
          },
          {
            confidence: 4,
            id: randomUUID(),
            last_studied: englishExamCreatedDate,
            priority: null,
            name: "English Subtopic 5.4",
            topic_id: topicIdEnglish5,
            order: 0,
          },
          {
            confidence: 7,
            id: randomUUID(),
            last_studied: englishExamCreatedDate,
            priority: null,
            name: "English Subtopic 5.5",
            topic_id: topicIdEnglish5,
            order: 0,
          },
        ],
      },
    ],
  },
  // {
  //   confidence: null,
  //   confidence_goal: 9,
  //   created_at: physicsExamCreatedDate,
  //   exam_date: "2024-08-25",
  //   last_studied: physicsExamCreatedDate,
  //   priority: null,
  //   name: "Physics Exam",
  //   id: examIdPhysics,
  //   subject_id: physicsID,
  //   user_id: userID,
  //   subjects: {
  //     subject_name: "Physics",
  //     id: physicsID,
  //     user_id: userID
  //   },

  //   topics: [
  //     {
  //       confidence: null,
  //       exam_id: examIdPhysics,
  //       id: topicIdPhysics1,
  //       last_studied: physicsExamCreatedDate,
  //       priority: null,
  //       name: "Physics Topic 1",
  //       order: 0,

  //       subtopics: [
  //         {
  //           confidence: 9,
  //           id: randomUUID(),
  //           last_studied: physicsExamCreatedDate,
  //           priority: null,
  //           name: "Physics Subtopic 1.1",
  //           topic_id: topicIdPhysics1,
  //           order: 0,
  //         },
  //         {
  //           confidence: 8,
  //           id: randomUUID(),
  //           last_studied: physicsExamCreatedDate,
  //           priority: null,
  //           name: "Physics Subtopic 1.2",
  //           topic_id: topicIdPhysics1,
  //           order: 0,
  //         },
  //         {
  //           confidence: null,
  //           id: randomUUID(),
  //           last_studied: physicsExamCreatedDate,
  //           priority: null,
  //           name: "Physics Subtopic 1.3",
  //           topic_id: topicIdPhysics1,
  //           order: 0,
  //         },
  //         {
  //           confidence: 6,
  //           id: randomUUID(),
  //           last_studied: physicsExamCreatedDate,
  //           priority: null,
  //           name: "Physics Subtopic 1.4",
  //           topic_id: topicIdPhysics1,
  //           order: 0,
  //         },
  //         {
  //           confidence: 4,
  //           id: randomUUID(),
  //           last_studied: physicsExamCreatedDate,
  //           priority: null,
  //           name: "Physics Subtopic 1.5",
  //           topic_id: topicIdPhysics1,
  //           order: 0,
  //         },
  //       ],
  //     },
  //     {
  //       confidence: null,
  //       exam_id: examIdPhysics,
  //       id: topicIdPhysics2,
  //       last_studied: physicsExamCreatedDate,
  //       priority: null,
  //       order: 0,
  //       name: "Physics Topic 2",
  //       subtopics: [
  //         {
  //           confidence: 3,
  //           id: randomUUID(),
  //           last_studied: physicsExamCreatedDate,
  //           priority: null,
  //           name: "Physics Subtopic 2.1",
  //           topic_id: topicIdPhysics2,
  //           order: 0,
  //         },
  //         {
  //           confidence: 5,
  //           id: randomUUID(),
  //           last_studied: physicsExamCreatedDate,
  //           priority: null,
  //           name: "Physics Subtopic 2.2",
  //           topic_id: topicIdPhysics2,
  //           order: 0,
  //         },
  //         {
  //           confidence: 2,
  //           id: randomUUID(),
  //           last_studied: physicsExamCreatedDate,
  //           priority: null,
  //           name: "Physics Subtopic 2.3",
  //           topic_id: topicIdPhysics2,
  //           order: 0,
  //         },
  //         {
  //           confidence: null,
  //           id: randomUUID(),
  //           last_studied: physicsExamCreatedDate,
  //           priority: null,
  //           name: "Physics Subtopic 2.4",
  //           topic_id: topicIdPhysics2,
  //           order: 0,
  //         },
  //         {
  //           confidence: 1,
  //           id: randomUUID(),
  //           last_studied: physicsExamCreatedDate,
  //           priority: null,
  //           name: "Physics Subtopic 2.5",
  //           topic_id: topicIdPhysics2,
  //           order: 0,
  //         },
  //       ],
  //     },
  //     {
  //       confidence: null,
  //       exam_id: examIdPhysics,
  //       id: topicIdPhysics3,
  //       last_studied: physicsExamCreatedDate,
  //       priority: null,
  //       name: "Physics Topic 3",
  //       order: 0,
  //       subtopics: [
  //         {
  //           confidence: 5,
  //           id: randomUUID(),
  //           last_studied: physicsExamCreatedDate,
  //           priority: null,
  //           name: "Physics Subtopic 3.1",
  //           order: 0,

  //           topic_id: topicIdPhysics3,
  //         },
  //         {
  //           confidence: 4,
  //           id: randomUUID(),
  //           last_studied: physicsExamCreatedDate,
  //           priority: null,
  //           name: "Physics Subtopic 3.2",
  //           order: 0,

  //           topic_id: topicIdPhysics3,
  //         },
  //         {
  //           confidence: null,
  //           id: randomUUID(),
  //           last_studied: physicsExamCreatedDate,
  //           priority: null,
  //           name: "Physics Subtopic 3.3",
  //           topic_id: topicIdPhysics3,
  //           order: 0,
  //         },
  //         {
  //           confidence: 1,
  //           id: randomUUID(),
  //           last_studied: physicsExamCreatedDate,
  //           priority: null,
  //           name: "Physics Subtopic 3.4",
  //           order: 0,

  //           topic_id: topicIdPhysics3,
  //         },
  //         {
  //           confidence: 3,
  //           id: randomUUID(),
  //           last_studied: physicsExamCreatedDate,
  //           priority: null,
  //           name: "Physics Subtopic 3.5",
  //           topic_id: topicIdPhysics3,
  //           order: 0,
  //         },
  //       ],
  //     },
  //     {
  //       confidence: null,
  //       exam_id: examIdPhysics,
  //       id: topicIdPhysics4,
  //       last_studied: physicsExamCreatedDate,
  //       priority: null,
  //       order: 0,

  //       name: "Physics Topic 4",
  //       subtopics: [
  //         {
  //           confidence: 4,
  //           id: randomUUID(),
  //           last_studied: physicsExamCreatedDate,
  //           priority: null,
  //           order: 0,

  //           name: "Physics Subtopic 4.1",
  //           topic_id: topicIdPhysics4,
  //         },
  //         {
  //           confidence: 6,
  //           id: randomUUID(),
  //           last_studied: physicsExamCreatedDate,
  //           priority: null,
  //           name: "Physics Subtopic 4.2",
  //           order: 0,

  //           topic_id: topicIdPhysics4,
  //         },
  //         {
  //           confidence: null,
  //           id: randomUUID(),
  //           last_studied: physicsExamCreatedDate,
  //           priority: null,
  //           name: "Physics Subtopic 4.3",
  //           order: 0,

  //           topic_id: topicIdPhysics4,
  //         },
  //         {
  //           confidence: 5,
  //           id: randomUUID(),
  //           last_studied: physicsExamCreatedDate,
  //           priority: null,
  //           name: "Physics Subtopic 4.4",
  //           topic_id: topicIdPhysics4,
  //           order: 0,
  //         },
  //         {
  //           confidence: 7,
  //           id: randomUUID(),
  //           last_studied: physicsExamCreatedDate,
  //           priority: null,
  //           name: "Physics Subtopic 4.5",
  //           order: 0,

  //           topic_id: topicIdPhysics4,
  //         },
  //       ],
  //     },
  //     {
  //       confidence: null,
  //       exam_id: examIdPhysics,
  //       id: topicIdPhysics5,
  //       last_studied: physicsExamCreatedDate,
  //       priority: null,
  //       name: "Physics Topic 5",
  //       order: 0,

  //       subtopics: [
  //         {
  //           confidence: null,
  //           id: randomUUID(),
  //           last_studied: physicsExamCreatedDate,
  //           priority: null,
  //           name: "Physics Subtopic 5.1",
  //           order: 0,

  //           topic_id: topicIdPhysics5,
  //         },
  //         {
  //           confidence: 9,
  //           id: randomUUID(),
  //           last_studied: physicsExamCreatedDate,
  //           priority: null,
  //           name: "Physics Subtopic 5.2",
  //           order: 0,

  //           topic_id: topicIdPhysics5,
  //         },
  //         {
  //           confidence: 4,
  //           id: randomUUID(),
  //           last_studied: physicsExamCreatedDate,
  //           priority: null,
  //           order: 0,

  //           name: "Physics Subtopic 5.3",
  //           topic_id: topicIdPhysics5,
  //         },
  //         {
  //           confidence: 6,
  //           id: randomUUID(),
  //           last_studied: physicsExamCreatedDate,
  //           priority: null,
  //           name: "Physics Subtopic 5.4",
  //           topic_id: topicIdPhysics5,
  //           order: 0,
  //         },
  //         {
  //           confidence: 3,
  //           id: randomUUID(),
  //           last_studied: physicsExamCreatedDate,
  //           priority: null,
  //           name: "Physics Subtopic 5.5",
  //           order: 0,

  //           topic_id: topicIdPhysics5,
  //         },
  //       ],
  //     },
  //   ],
  // },
];
